### ISSUE TITLE
Unable to install mediapipe

### ISSUE THREAD

**Issue by rudian** [nuralogix/dfx-demo-py#13]
![image](https://github.com/nuralogix/dfx-demo-py/assets/7321758/4575c64a-0398-4c44-a41c-2d1f75c4f6e2)

pip install -e ".[mediapipe]" -f wheels/

I unable to run this command

**Comment by sambhare** [comment]
Are you on an ARM-based Mac? We haven't updated our SDK to support ARM-based Macs yet. We have a release coming soon which support them.

**Comment by TerenceStupple** [comment]
Any update on this. Having the same issue.
Need a libdfx to run on non-intel machines.

**Comment by sambhare** [comment]
We're working on building libdfx on ARM macOS machines and will be releasing it soon. I'll ping this ticket again once it's on our website.

**Comment by sambhare** [comment]
Hello, we've released the macOS ARM64 builds of the libdfxpython wheels. You can find them here: https://deepaffex.ai/developers-sdk/ We've also updated the dependencies on this project to encompass mediapipe 0.9.x and 0.10.x, so please also update your local copy.

**Comment by TerenceStupple** [comment]
Thanks Rajas.

FYI I had to run the pip install with the --use-pep517 flag to get it to work.

`pip install -e ".[mediapipe]" -f wheels/ --use-pep517 `
