### ISSUE TITLE
SNR = -100 

### ISSUE THREAD

**Issue by ark1375** [nuralogix/dfx-demo-py#2]
I'm trying to do a measurement, but the only thing I receive is SNR = -100.
```
>python dfxdemo.py measure make my-video2.mp4
Created DFX Factory: libdfx2 version 4.4.1 - May 27, 2020
Retrieved new DFX SDK config data with md5: 24d0bb4bde33fc9d0a7cdc9ec5354d6b
Config updated in ./config.json
[2020-08-08 17:56:45.031] [dfx] [info] Loading: mobile20200702 (64-bit version)
[2020-08-08 17:56:45.038] [dfx] [info] Loading:
[2020-08-08 17:56:45.039] [dfx] [info] Loaded:
[2020-08-08 17:56:45.040] [dfx] [info] Loaded: mobile20200702
Created DFX Collector:
    mode: discrete
    number chunks: 4
    chunk duration: 5.010000228881836s
Created measurement 315f76df-fb4b-4af3-b88d-a005d143acd4
Extraction started
Sent chunk 0
Received chunk 0
  SNR: -100.0
Sent chunk 1
Received chunk 1
  SNR: -100.0
Sent chunk 2
Received chunk 2
  SNR: -100.0
Sent chunk 3
Extraction complete, waiting for results
Received chunk 3
  SNR: -100.0
Measurement complete
Config updated in ./config.json
Measurement 315f76df-fb4b-4af3-b88d-a005d143acd4 completed
Use 'python dfxdemo.py measure get' to get comprehensive results
```

**Comment by sambhare** [comment]
This is happening because most likely the video you are using doesn't seem to have enough quality for us to be able to extract blood-flow information successfully. 

Could you please try again using the[ Sample Data video](https://s3.us-east-2.amazonaws.com/nuralogix-assets/dfx-sdk/dfxsdk-example-data.zip) posted on our SDK site?

**Comment by ark1375** [comment]
I tried the sample data and it worked well, but I used multiple devices
with various different settings for recording video and it didn't work. Is
there a recommended quality settings for the videos??

**Comment by sambhare** [comment]
It's hard to predict why a specific video will not work properly but our overall guidelines are to try and measure in good lighting and to use the best possible video quality. Poor lighting and codec compression will both negatively affect SNR. 

Please reach out to use using the [Contact link on the DeepAffex website](https://deepaffex.ai/) and perhaps we can analyze your videos directly.
