### ISSUE TITLE
DFX Dashboard - Developer account generation broken

### ISSUE THREAD

**Issue by ChrisStei** [nuralogix/dfx-demo-py#6]
It seems like the account generation at https://dashboard.deepaffex.ai/login (as explained in the README) is broken and it is thus not possible to get a licence for testing the dfx-demo.
When signing up, an "internal error" pops up just after accepting the terms and conditions.
When trying to sign up once again after that, a "user with this email address already exists".

**Comment by sambhare** [comment]
Hello ChrisStei, thanks for reporting this. We'll investigate it and get back to you.

**Comment by sambhare** [comment]
Issue is confirmed. We'll let you know when it's fixed.

**Comment by ChrisStei** [comment]
@sambhare I confirm that the issue is solved. I will close it now. If possible, could you reset the account with email address christian.steinmetz@arrk-engineering.com in order for me to re-create the account? The "A User with this email already exists"-error appears at the moment, although I was not able to login.

**Comment by sambhare** [comment]
Hi Chris, can you try the "Forgot password" on the Dashboard and reset your password for that email? If that doesn't work, then I will ask the team to reset it.
